# Generated by Django 3.2 on 2023-10-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
