# Generated by Django 3.2 on 2023-10-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
    ]
